services:
  - type: web
    name: bot-2025
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    branch: main
    environment:
      pythonVersion: 3.10
